default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgresql
  password:

development:
  <<: *default
  database: "dev_hexagonal"

test:
  <<: *default
  database: "test_hexagonal"

production:
  <<: *default
  database: "production_hexagonal"
